// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiaosohnkcpzxszphpqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpYW9zb2hua2NwenhzenBocHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzY3NjYsImV4cCI6MjA3MzM1Mjc2Nn0.wyWLAHN-oJXFGRhsr_q3pNcgyWuW_GWYpvsXB2obLVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});